title: HASLAB.ORG
description: The computer world is a world of dialect.
permalink: date
exclude: [project, src, build.sbt, CNAME, LICENSE, README.md, bin, Gemfile, Gemfile.lock]

baidu_tongji: 5dd90fa2a437c8398a6a160a4fbd5607

collections:
  docs:
    title: 文档
    output: true
  lectures:
    title: 课程
    output: true

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    day: /:year/:month/:day/
    tag: /tag/:name/
    category: /category/:name/

paginate: 24
paginate_path: /blog/:num/

plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-github
  - jekyll-github-metadata
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
