title: HASLAB.ORG
description: The computer world is a world of dialect.
permalink: /post/:title:output_ext
exclude: [project, src, build.sbt, CNAME, LICENSE, README.md, bin]

collections:
  docs:
    title: 文档
    output: true
  lectures:
    title: 课程
    output: true

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    day: /:year/:month/:day/
    tag: /tag/:name/
    category: /category/:name/

paginate: 12
paginate_path: /blog/:num/

plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-github
  - jekyll-github-metadata
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
